-- DROP USER PYUSER;

CREATE USER PYUSER
-- IDENTIFIED BY <password>
;

CREATE TABLE "PYUSER"."DEPARTMENT" 
   (	"DEPARTMENT_ID" CHAR(8), 
	"DEPARTMENT_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "PK_DEPATRTMENT" PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "PYUSER"."PK_DEPATRTMENT" ON "PYUSER"."DEPARTMENT" ("DEPARTMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE PYUSER.DEPARTMENT IS '系表';
COMMENT ON COLUMN PYUSER.DEPARTMENT.DEPARTMENT_ID IS '系编号';
COMMENT ON COLUMN PYUSER.DEPARTMENT.DEPARTMENT_NAME IS '系名称';

CREATE TABLE "PYUSER"."GRADUATION" 
   (	"GRADUATION_ID" CHAR(10), 
	"GRADUATION_TOPIC" VARCHAR2(255) NOT NULL ENABLE, 
	"GRADUATION_TEACHER_ID" CHAR(10), 
	"GRADUATION_KIND" VARCHAR2(255) NOT NULL ENABLE, 
	"GRADUATION_INTRODUCTION" VARCHAR2(255) NOT NULL ENABLE, 
	"GRADUATION_SUBDATE" DATE, 
	"GRADUATION_STATE" VARCHAR2(255), 
	"GRADUATION_APPDATE" DATE, 
	"GRADUATION_DEADLINE" DATE, 
	"GRADUATION_WORD" BLOB, 
	 CONSTRAINT "PK_GRADUATION_ID" PRIMARY KEY ("GRADUATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CH_GRADUATION_STATE" CHECK (Graduation_state in ('通过','拒绝','未审核')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("GRADUATION_WORD") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

ALTER TABLE "PYUSER"."GRADUATION" ADD CONSTRAINT "FK_GRADUATION_TEACHER_ID" FOREIGN KEY ("GRADUATION_TEACHER_ID")
	  REFERENCES "PYUSER"."TEACHER" ("TEACHER_ID") ENABLE;

CREATE UNIQUE INDEX "PYUSER"."PK_GRADUATION_ID" ON "PYUSER"."GRADUATION" ("GRADUATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "PYUSER"."SYS_IL0000023091C00010$$" ON "PYUSER"."GRADUATION" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE PYUSER.GRADUATION IS '毕业设计信息表';
COMMENT ON COLUMN PYUSER.GRADUATION.GRADUATION_ID IS '毕设id';
COMMENT ON COLUMN PYUSER.GRADUATION.GRADUATION_TEACHER_ID IS '指导教师工号';
COMMENT ON COLUMN PYUSER.GRADUATION.GRADUATION_KIND IS '研究方向';
COMMENT ON COLUMN PYUSER.GRADUATION.GRADUATION_INTRODUCTION IS '大致介绍';
COMMENT ON COLUMN PYUSER.GRADUATION.GRADUATION_SUBDATE IS '提交时间';
COMMENT ON COLUMN PYUSER.GRADUATION.GRADUATION_STATE IS '审核状态';
COMMENT ON COLUMN PYUSER.GRADUATION.GRADUATION_APPDATE IS '审核时间';

CREATE TABLE "PYUSER"."SCORE" 
   (	"SCORE_STUDENT_ID" CHAR(10), 
	"SCORE_TEACHER_ID" CHAR(10), 
	"SCORE_GRADUATION_ID" CHAR(10), 
	"SCORE_" VARCHAR2(3), 
	 CONSTRAINT "PK_SCORE_STUDENT_ID" PRIMARY KEY ("SCORE_STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "PYUSER"."SCORE" ADD CONSTRAINT "FK_SCORE_GRADUATION_ID" FOREIGN KEY ("SCORE_GRADUATION_ID")
	  REFERENCES "PYUSER"."GRADUATION" ("GRADUATION_ID") ENABLE;
  ALTER TABLE "PYUSER"."SCORE" ADD CONSTRAINT "FK_SCORE_STUDENT_ID" FOREIGN KEY ("SCORE_STUDENT_ID")
	  REFERENCES "PYUSER"."STUDENT" ("STUDENT_ID") ENABLE;
  ALTER TABLE "PYUSER"."SCORE" ADD CONSTRAINT "FK_SCORE_TEACHER_ID" FOREIGN KEY ("SCORE_TEACHER_ID")
	  REFERENCES "PYUSER"."TEACHER" ("TEACHER_ID") ENABLE;

CREATE UNIQUE INDEX "PYUSER"."PK_SCORE_STUDENT_ID" ON "PYUSER"."SCORE" ("SCORE_STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE PYUSER.SCORE IS '分数表';
COMMENT ON COLUMN PYUSER.SCORE.SCORE_STUDENT_ID IS '学生学号';
COMMENT ON COLUMN PYUSER.SCORE.SCORE_TEACHER_ID IS '教师工号';
COMMENT ON COLUMN PYUSER.SCORE.SCORE_GRADUATION_ID IS '毕设ID';
COMMENT ON COLUMN PYUSER.SCORE.SCORE_ IS '最终分数';

CREATE TABLE "PYUSER"."STUDENT" 
   (	"STUDENT_ID" CHAR(10), 
	"STUDENT_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"STUDENT_SEX" VARCHAR2(3), 
	"STUDENT_DEPARTMENT_ID" CHAR(8) NOT NULL ENABLE, 
	"STUDENT_SUBJECT" VARCHAR2(30) NOT NULL ENABLE, 
	"STUDENT_NUMBER" CHAR(11) NOT NULL ENABLE, 
	"STUDENT_EMAIL" VARCHAR2(30) NOT NULL ENABLE, 
	"STUDENT_CLASS" VARCHAR2(10), 
	 CONSTRAINT "CH_STUDENT_SEX" CHECK (Student_sex in ('男','女')) ENABLE, 
	 CONSTRAINT "PK_STUDENT_ID" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "PYUSER"."STUDENT" ADD CONSTRAINT "FK_STUDENT_DEPARTMENT_ID" FOREIGN KEY ("STUDENT_DEPARTMENT_ID")
	  REFERENCES "PYUSER"."DEPARTMENT" ("DEPARTMENT_ID") ENABLE;

CREATE UNIQUE INDEX "PYUSER"."PK_STUDENT_ID" ON "PYUSER"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE PYUSER.STUDENT IS '学生信息表';
COMMENT ON COLUMN PYUSER.STUDENT.STUDENT_ID IS '学生学号';
COMMENT ON COLUMN PYUSER.STUDENT.STUDENT_NAME IS '学生姓名';
COMMENT ON COLUMN PYUSER.STUDENT.STUDENT_SEX IS '学生性别';
COMMENT ON COLUMN PYUSER.STUDENT.STUDENT_DEPARTMENT_ID IS '学生院系ID';
COMMENT ON COLUMN PYUSER.STUDENT.STUDENT_SUBJECT IS '学生专业';
COMMENT ON COLUMN PYUSER.STUDENT.STUDENT_NUMBER IS '学生电话';
COMMENT ON COLUMN PYUSER.STUDENT.STUDENT_EMAIL IS '学生邮箱';

CREATE TABLE "PYUSER"."TEACHER" 
   (	"TEACHER_ID" CHAR(10), 
	"TEACHER_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"TEACHER_SEX" CHAR(3), 
	"TEACHER_TITLE" VARCHAR2(30), 
	"TEACHER_DEPARTMENT_ID" CHAR(8), 
	"TEACHER_RESEARCH" VARCHAR2(255), 
	"TEACHER_NUMBER" CHAR(11) NOT NULL ENABLE, 
	"TEACHER_EMAIL" VARCHAR2(30) NOT NULL ENABLE, 
	"TEACHER_LEADERSHIP_ID" CHAR(10), 
	"TEACHER_GRADNUMBER" NUMBER(3,0), 
	 CONSTRAINT "PK_TEACHER_SEX" CHECK (Teacher_sex in ('男','女')) ENABLE, 
	 CONSTRAINT "PK_TEACHER_TITLE" CHECK (Teacher_title IN('教授'，'副教授'，'讲师','助教')) ENABLE, 
	 CONSTRAINT "PK_TEACHER_ID" PRIMARY KEY ("TEACHER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "PYUSER"."TEACHER" ADD CONSTRAINT "FK_TEACHER_DEPARTMENT_ID" FOREIGN KEY ("TEACHER_DEPARTMENT_ID")
	  REFERENCES "PYUSER"."DEPARTMENT" ("DEPARTMENT_ID") ENABLE;

CREATE UNIQUE INDEX "PYUSER"."PK_TEACHER_ID" ON "PYUSER"."TEACHER" ("TEACHER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE PYUSER.TEACHER IS '教师信息表';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_ID IS '教师编号';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_NAME IS '教师姓名';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_SEX IS '教师性别';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_TITLE IS '职称';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_DEPARTMENT_ID IS '系编号';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_RESEARCH IS '研究方向';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_NUMBER IS '教师电话';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_EMAIL IS '教师邮箱';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_LEADERSHIP_ID IS '系主任编号';
COMMENT ON COLUMN PYUSER.TEACHER.TEACHER_GRADNUMBER IS '教师已有的题目数量';

CREATE TABLE "PYUSER"."THEME" 
   (	"THEME_ID" CHAR(10), 
	"THEME_STUDENT" CHAR(10), 
	"THEME_TEACHER" CHAR(10), 
	"THEME_STATE" VARCHAR2(20), 
	"THEME_DEADLINE" DATE, 
	"THEME_WORD" BLOB, 
	 CONSTRAINT "CH_THEME_STATE" CHECK (Theme_State in ('同意','拒绝','未审核')) ENABLE, 
	 CONSTRAINT "PK_THEME" PRIMARY KEY ("THEME_ID", "THEME_STUDENT", "THEME_TEACHER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("THEME_WORD") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

ALTER TABLE "PYUSER"."THEME" ADD CONSTRAINT "FK_THEME_ID" FOREIGN KEY ("THEME_ID")
	  REFERENCES "PYUSER"."GRADUATION" ("GRADUATION_ID") ENABLE;
  ALTER TABLE "PYUSER"."THEME" ADD CONSTRAINT "FK_THEME_STUDENT" FOREIGN KEY ("THEME_STUDENT")
	  REFERENCES "PYUSER"."STUDENT" ("STUDENT_ID") ENABLE;
  ALTER TABLE "PYUSER"."THEME" ADD CONSTRAINT "FK_THEME_TEACHER" FOREIGN KEY ("THEME_TEACHER")
	  REFERENCES "PYUSER"."TEACHER" ("TEACHER_ID") ENABLE;

CREATE UNIQUE INDEX "PYUSER"."PK_THEME" ON "PYUSER"."THEME" ("THEME_ID", "THEME_STUDENT", "THEME_TEACHER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "PYUSER"."SYS_IL0000023097C00006$$" ON "PYUSER"."THEME" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE PYUSER.THEME IS '毕业设计信息，学生，教师信息关联表';
COMMENT ON COLUMN PYUSER.THEME.THEME_ID IS '毕设ID';
COMMENT ON COLUMN PYUSER.THEME.THEME_STUDENT IS '学生学号';
COMMENT ON COLUMN PYUSER.THEME.THEME_TEACHER IS '教师工号';
COMMENT ON COLUMN PYUSER.THEME.THEME_STATE IS '审核状态';
COMMENT ON COLUMN PYUSER.THEME.THEME_DEADLINE IS '截止时间';

CREATE TABLE "PYUSER"."TOPICLIMITS" 
   (	"TOPICLIMITS_YEARS" CHAR(4), 
	"TOPICLIMITS_MAX" VARCHAR2(4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE PYUSER.TOPICLIMITS IS '每年论文数限制表';
COMMENT ON COLUMN PYUSER.TOPICLIMITS.TOPICLIMITS_YEARS IS '年份';
COMMENT ON COLUMN PYUSER.TOPICLIMITS.TOPICLIMITS_MAX IS '最大题目数量';

CREATE TABLE "PYUSER"."USER_ADMIN" 
   (	"USER_ADMIN_ID" CHAR(10), 
	"USER_ADMIN_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ADMIN_PASSWORDHASH" VARCHAR2(255) NOT NULL ENABLE, 
	"USER_ADMIN_NUMBER" CHAR(11) NOT NULL ENABLE, 
	 CONSTRAINT "PK_USER_ADMIN" PRIMARY KEY ("USER_ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "PYUSER"."PK_USER_ADMIN" ON "PYUSER"."USER_ADMIN" ("USER_ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE PYUSER.USER_ADMIN IS '管理员表';
COMMENT ON COLUMN PYUSER.USER_ADMIN.USER_ADMIN_ID IS '管理员ID';
COMMENT ON COLUMN PYUSER.USER_ADMIN.USER_ADMIN_NAME IS '管理员姓名';
COMMENT ON COLUMN PYUSER.USER_ADMIN.USER_ADMIN_PASSWORDHASH IS '管理员密码';
COMMENT ON COLUMN PYUSER.USER_ADMIN.USER_ADMIN_NUMBER IS '管理员电话';

CREATE TABLE "PYUSER"."USER_STUDENT" 
   (	"USER_STUDENT_ID" CHAR(10), 
	"USER_STUDENT_PASSWORDHASH" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "PK_USER_STUDENT_ID" PRIMARY KEY ("USER_STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "PYUSER"."USER_STUDENT" ADD CONSTRAINT "FK_USER_STUDENT_ID" FOREIGN KEY ("USER_STUDENT_ID")
	  REFERENCES "PYUSER"."STUDENT" ("STUDENT_ID") ENABLE;

CREATE UNIQUE INDEX "PYUSER"."PK_USER_STUDENT_ID" ON "PYUSER"."USER_STUDENT" ("USER_STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE PYUSER.USER_STUDENT IS '学生账号表';
COMMENT ON COLUMN PYUSER.USER_STUDENT.USER_STUDENT_ID IS '学生学号';
COMMENT ON COLUMN PYUSER.USER_STUDENT.USER_STUDENT_PASSWORDHASH IS '学生密码';

CREATE TABLE "PYUSER"."USER_TEACHER" 
   (	"USER_TEACHER_ID" CHAR(10), 
	"USER_TEACHER_PASSWORDHASH" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "PK_USER_TEACHER_ID" PRIMARY KEY ("USER_TEACHER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "PYUSER"."USER_TEACHER" ADD CONSTRAINT "FK_USER_TEACHER_ID" FOREIGN KEY ("USER_TEACHER_ID")
	  REFERENCES "PYUSER"."TEACHER" ("TEACHER_ID") ENABLE;

CREATE UNIQUE INDEX "PYUSER"."PK_USER_TEACHER_ID" ON "PYUSER"."USER_TEACHER" ("USER_TEACHER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE PYUSER.USER_TEACHER IS '教师账号表';
COMMENT ON COLUMN PYUSER.USER_TEACHER.USER_TEACHER_ID IS '教师编号';
COMMENT ON COLUMN PYUSER.USER_TEACHER.USER_TEACHER_PASSWORDHASH IS '教师密码';

CREATE SEQUENCE PYUSER.SEQTEST INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 5 NOORDER ;
